# Generated by Django 5.2.7 on 2026-08-01 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planillas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('planilla_oficial', 'Planilla oficial (PDF SRT)'), ('protocolo_completo', 'Protocolo completo (PDF SRT)'), ('detalle_factor', 'Detalle técnico de un factor'), ('informe_factor', 'Informe profesional de un factor'), ('informe_evaluacion', 'Informe profesional consolidado'), ('paquete_zip', 'Paquete documental (ZIP)'), ('excel_editable', 'Copia de trabajo editable (XLS)')], max_length=32)),
                ('detalle', models.CharField(blank=True, default='', help_text='Slug de planilla o factor. Nunca datos personales.', max_length=120)),
                ('bytes_entregados', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descargas', to='planillas.evaluacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Descarga de export',
                'verbose_name_plural': 'Descargas de export',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['evaluacion', 'creado_en'], name='exportacion_evaluac_5629a4_idx')],
            },
        ),
    ]
