# Generated by Django 5.2.7 on 2026-08-01 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportaciones', '0001_initial'),
        ('planillas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('planilla_oficial', 'Planilla oficial (PDF SRT)'), ('protocolo_completo', 'Protocolo completo (PDF SRT)'), ('detalle_factor', 'Detalle técnico de un factor'), ('informe_factor', 'Informe profesional de un factor'), ('informe_evaluacion', 'Informe profesional consolidado'), ('paquete_zip', 'Paquete documental (ZIP)'), ('excel_editable', 'Copia de trabajo editable (XLS)')], max_length=32)),
                ('factor_slug', models.SlugField(blank=True, default='')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('listo', 'Listo'), ('error', 'Error'), ('obsoleto', 'Obsoleto (los datos cambiaron)')], default='pendiente', max_length=16)),
                ('payload_json', models.JSONField(blank=True, default=dict, help_text='Payload exacto que se envió al modelo. Es la evidencia.')),
                ('inputs_hash', models.CharField(db_index=True, max_length=64)),
                ('contenido_markdown', models.TextField(blank=True, default='')),
                ('modelo_llm', models.CharField(blank=True, default='', max_length=64)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=16)),
                ('schema_version', models.CharField(default='1.0.0', max_length=16)),
                ('tokens_prompt', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_respuesta', models.PositiveIntegerField(blank=True, null=True)),
                ('duracion_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_detalle', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_generados', to='planillas.evaluacion')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Informe generado',
                'verbose_name_plural': 'Informes generados',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['evaluacion', 'tipo', 'factor_slug'], name='exportacion_evaluac_88148f_idx'), models.Index(fields=['inputs_hash'], name='exportacion_inputs__4eb5a5_idx')],
                'constraints': [models.UniqueConstraint(fields=('evaluacion', 'tipo', 'factor_slug', 'inputs_hash'), name='uniq_informe_por_huella')],
            },
        ),
    ]
