# Generated by Django 5.2.10 on 2026-02-04 16:48

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_type', models.CharField(choices=[('professional', 'Profesional SySO'), ('trainee', 'Trabajador')], default='trainee', max_length=20, verbose_name='Tipo de usuario')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Apellido')),
                ('full_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre completo')),
                ('username', models.CharField(blank=True, help_text='Usuario para login de profesionales', max_length=50, null=True, unique=True, verbose_name='Usuario')),
                ('dni', models.CharField(blank=True, default='', max_length=15, validators=[django.core.validators.RegexValidator('^\\d{7,8}$', 'DNI inválido (7-8 dígitos)')], verbose_name='DNI')),
                ('profession', models.CharField(blank=True, default='', help_text='Ej: Lic. en Higiene y Seguridad, Médico Laboral, Ergónomo', max_length=100, verbose_name='Profesión')),
                ('license_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Matrícula profesional')),
                ('cuil', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='CUIL')),
                ('job_title', models.CharField(blank=True, default='', max_length=200, verbose_name='Puesto de trabajo')),
                ('company_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Empresa')),
                ('employer_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email del empleador')),
                ('safety_responsible_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email del responsable SySO')),
                ('subscription_tier', models.CharField(choices=[('free', 'Gratuito'), ('basic', 'Básico'), ('premium', 'Premium')], default='free', max_length=20, verbose_name='Plan de suscripción')),
                ('subscription_status', models.CharField(choices=[('none', 'Sin suscripción'), ('active', 'Activa'), ('expired', 'Vencida'), ('cancelled', 'Cancelada')], default='none', max_length=20, verbose_name='Estado de suscripción')),
                ('subscription_expires', models.DateTimeField(blank=True, null=True, verbose_name='Vencimiento de suscripción')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-date_joined'],
            },
        ),
    ]
