# Generated by Django 5.2.10 on 2026-03-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('professional', 'Profesional SySO'), ('trainee', 'Trabajador'), ('company', 'Empresa')], default='trainee', max_length=20, verbose_name='Tipo de usuario'),
        ),
    ]
