# Generated by Django 5.2.10 on 2026-02-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineeuser',
            name='employer_email',
            field=models.EmailField(blank=True, default='', help_text='Email del empleador para recibir copia del certificado', max_length=254, verbose_name='Email del empleador'),
        ),
        migrations.AddField(
            model_name='traineeuser',
            name='safety_responsible_email',
            field=models.EmailField(blank=True, default='', help_text='Email del responsable de Seg. e Higiene, Salud o Ergonomía', max_length=254, verbose_name='Email del responsable de Seguridad/Higiene/Ergonomía'),
        ),
    ]
