# Generated by Django 5.2.10 on 2026-03-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_company_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_visible_in_directory',
            field=models.BooleanField(default=False, help_text='Si está activo, este profesional será visible en el directorio para empresas.', verbose_name='Visible en directorio'),
        ),
    ]
