# Generated by Django 5.2.10 on 2026-08-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_is_visible_in_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='attribution_campaign',
            field=models.CharField(blank=True, db_index=True, default='', help_text="'ergoreach' identifica al copiloto de marketing", max_length=64, verbose_name='Campaña (utm_campaign)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='attribution_content',
            field=models.CharField(blank=True, db_index=True, default='', help_text='short_id del borrador que originó la visita', max_length=64, verbose_name='Contenido (utm_content)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='attribution_first_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Primer contacto'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='attribution_landing_path',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Primera página vista'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='attribution_medium',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Medio (utm_medium)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='attribution_referrer_host',
            field=models.CharField(blank=True, default='', help_text='Solo el host, nunca la URL completa (minimización)', max_length=128, verbose_name='Host de procedencia'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='attribution_source',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Origen (utm_source)'),
        ),
    ]
