# Generated by Django 5.2.10 on 2026-02-04 16:48

import apps.certificates.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(default=apps.certificates.models.default_valid_until)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_error', models.TextField(blank=True, default='')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='quiz.quizattempt')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='training.trainingmodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-issued_at'],
            },
        ),
    ]
