# Generated by Django 5.2.10 on 2026-02-16 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0002_add_icon_color_order_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresencialSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(verbose_name='Fecha de la sesión')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='Ubicación')),
                ('participants_count', models.PositiveIntegerField(default=0, verbose_name='Cantidad de participantes')),
                ('quiz_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Score del quiz')),
                ('quiz_passed', models.BooleanField(default=False, verbose_name='Quiz aprobado')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas / Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencial_sessions', to='training.trainingmodule', verbose_name='Módulo')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencial_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Sesión presencial',
                'verbose_name_plural': 'Sesiones presenciales',
                'ordering': ['-session_date', '-created_at'],
            },
        ),
    ]
