# Generated by Django 5.2.10 on 2026-01-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identificador único para la URL.', unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Título del módulo')),
                ('youtube_id', models.CharField(help_text='Solo el ID del video (ej: IIgZp_NbsAE), no la URL completa.', max_length=32)),
                ('intro_md', models.TextField(blank=True, default='', verbose_name='Introducción (Markdown)')),
                ('material_md', models.TextField(blank=True, default='', verbose_name='Material de lectura')),
                ('transcript_md', models.TextField(blank=True, default='', verbose_name='Transcripción del video')),
                ('is_active', models.BooleanField(default=False, verbose_name='¿Está activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Módulo de capacitación',
                'verbose_name_plural': 'Módulos de capacitación',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
