# Generated by Django 5.2.10 on 2026-02-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingmodule',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Módulo de capacitación', 'verbose_name_plural': 'Módulos de capacitación'},
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='color',
            field=models.CharField(default='#28a745', help_text='Color hex para el card (ej: #28a745)', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Descripción breve para mostrar en el menú de capacitaciones.', verbose_name='Descripción corta'),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='icon',
            field=models.CharField(default='bi-book', help_text='Clase de Bootstrap Icons (ej: bi-body-text, bi-lightning-charge)', max_length=50),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Orden de aparición en el menú (menor = primero)'),
        ),
    ]
