# Generated by Django 5.2.10 on 2026-02-17 00:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_add_icon_color_order_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacitacionLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', help_text='Nombre interno para identificar el link (ej: Planta Norte - Turno Mañana).', max_length=120, verbose_name='Etiqueta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Opcional. Si se define, el link deja de ser usable después de esta fecha/hora.', null=True, verbose_name='Vence el')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='Cantidad de accesos')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitacion_links', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitacion_links', to='training.trainingmodule', verbose_name='Módulo de capacitación')),
            ],
            options={
                'verbose_name': 'Link de capacitación',
                'verbose_name_plural': 'Links de capacitación',
                'ordering': ['-created_at'],
            },
        ),
    ]
