# Generated by Django 5.2.10 on 2026-02-17 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_add_capacitacion_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkShareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_to_email', models.EmailField(max_length=254, verbose_name='Email destinatario')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_logs', to='training.capacitacionlink', verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Envío de link',
                'verbose_name_plural': 'Envíos de links',
                'ordering': ['-shared_at'],
            },
        ),
    ]
