# Generated by Django 5.2.10 on 2026-02-28 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_add_link_share_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodule',
            name='assigned_professionals',
            field=models.ManyToManyField(blank=True, help_text='Profesionales que pueden ver y acceder a esta capacitación.', related_name='personalized_trainings', to=settings.AUTH_USER_MODEL, verbose_name='Profesionales asignados'),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='company_name_custom',
            field=models.CharField(blank=True, default='', help_text='Nombre de la empresa o cliente para esta capacitación personalizada.', max_length=200, verbose_name='Empresa/Cliente'),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='custom_notes',
            field=models.TextField(blank=True, default='', help_text='Notas internas sobre esta capacitación (no visibles para los usuarios).', verbose_name='Notas internas'),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='is_personalized',
            field=models.BooleanField(default=False, help_text='Si es True, solo los profesionales asignados pueden ver esta capacitación.', verbose_name='¿Es personalizada?'),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='Profesional que solicitó esta capacitación personalizada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_trainings', to=settings.AUTH_USER_MODEL, verbose_name='Solicitada por'),
        ),
    ]
