"""Crea las tablas aditivas de reportes y adjuntos privados."""

# Generated by Django 5.2.10 on 2026-08-11 22:06

import apps.feedback.models
import apps.feedback.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporter_name', models.CharField(max_length=200)),
                ('reporter_email', models.EmailField(max_length=254)),
                ('reporter_profession', models.CharField(blank=True, max_length=100)),
                ('reporter_license_number', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('bug', 'Error'), ('improvement', 'Mejora'), ('question', 'Consulta'), ('other', 'Otro')], max_length=20)),
                ('subject', models.CharField(max_length=160)),
                ('affected_screen', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('reproduction_steps', models.TextField(blank=True)),
                ('expected_result', models.TextField(blank=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('email_status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('email_attempts', models.PositiveSmallIntegerField(default=0)),
                ('email_error_code', models.CharField(blank=True, max_length=120)),
                ('last_email_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de feedback',
                'verbose_name_plural': 'Reportes de feedback',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FeedbackAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, storage=apps.feedback.storage.PrivateFeedbackStorage(), upload_to=apps.feedback.models.feedback_attachment_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feedback.feedbackreport')),
            ],
            options={
                'verbose_name': 'Adjunto de feedback',
                'verbose_name_plural': 'Adjuntos de feedback',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='feedbackreport',
            index=models.Index(fields=['professional', '-created_at'], name='feedback_fe_profess_5485ea_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackreport',
            index=models.Index(fields=['email_status', 'created_at'], name='feedback_fe_email_s_cd570d_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackreport',
            index=models.Index(fields=['category', '-created_at'], name='feedback_fe_categor_b89031_idx'),
        ),
    ]
