# Generated by Django 5.2.10 on 2026-03-05 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=300, verbose_name='Razón social')),
                ('nombre_comercial', models.CharField(blank=True, default='', help_text='Nombre comercial o fantasía (opcional).', max_length=300, verbose_name='Nombre comercial')),
                ('cuit', models.CharField(help_text='CUIT de la empresa (formato: XX-XXXXXXXX-X o solo dígitos).', max_length=20, unique=True, verbose_name='CUIT')),
                ('rubro', models.CharField(blank=True, default='', max_length=200, verbose_name='Rubro / Actividad')),
                ('cantidad_trabajadores', models.PositiveIntegerField(default=0, verbose_name='Cantidad aproximada de trabajadores')),
                ('contacto_nombre', models.CharField(max_length=200, verbose_name='Nombre del contacto principal')),
                ('contacto_cargo', models.CharField(blank=True, default='', max_length=200, verbose_name='Cargo del contacto')),
                ('contacto_telefono', models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono de contacto')),
                ('domicilio', models.CharField(blank=True, default='', max_length=400, verbose_name='Domicilio / Ubicación principal')),
                ('localidad', models.CharField(blank=True, default='', max_length=200, verbose_name='Localidad')),
                ('provincia', models.CharField(blank=True, default='', max_length=100, verbose_name='Provincia')),
                ('account_status', models.CharField(choices=[('active', 'Activa'), ('pending_validation', 'Pendiente de validación'), ('suspended', 'Suspendida'), ('inactive', 'Inactiva')], default='active', max_length=30, verbose_name='Estado de cuenta')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo de la empresa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'company'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de acceso')),
            ],
            options={
                'verbose_name': 'Perfil de Empresa',
                'verbose_name_plural': 'Perfiles de Empresas',
                'ordering': ['razon_social'],
            },
        ),
    ]
