# Generated by Django 5.2.10 on 2026-03-05 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_create_company_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Legajo')),
                ('department', models.CharField(blank=True, default='', max_length=200, verbose_name='Sector')),
                ('position', models.CharField(blank=True, default='', max_length=200, verbose_name='Puesto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha baja')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='company.companyprofile', verbose_name='Empresa')),
                ('worker', models.ForeignKey(limit_choices_to={'user_type': 'trainee'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Trabajador de empresa',
                'verbose_name_plural': 'Trabajadores de empresa',
                'ordering': ['company', 'worker__last_name', 'worker__first_name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'worker'), name='uq_company_worker')],
            },
        ),
    ]
