# Generated by Django 5.2.10 on 2026-03-06 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_create_company_worker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('event_type', models.CharField(choices=[('training_due', 'Vencimiento de capacitación'), ('certificate_expiry', 'Vencimiento de certificado'), ('professional_visit', 'Visita de profesional'), ('evaluation_due', 'Evaluación pendiente'), ('reminder', 'Recordatorio'), ('other', 'Otro')], default='reminder', max_length=30, verbose_name='Tipo de evento')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('overdue', 'Vencido'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridad')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora de inicio')),
                ('due_at', models.DateTimeField(verbose_name='Fecha/hora límite')),
                ('related_object_type', models.CharField(blank=True, default='', help_text='Ej: certificate, training_module', max_length=50, verbose_name='Tipo de objeto relacionado')),
                ('related_object_id', models.CharField(blank=True, default='', max_length=100, verbose_name='ID del objeto relacionado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_agenda_events', to=settings.AUTH_USER_MODEL, verbose_name='Profesional asignado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_events', to='company.companyprofile', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agenda_events', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_events', to=settings.AUTH_USER_MODEL, verbose_name='Trabajador relacionado')),
            ],
            options={
                'verbose_name': 'Evento de agenda',
                'verbose_name_plural': 'Eventos de agenda',
                'ordering': ['due_at', '-priority'],
                'indexes': [models.Index(fields=['company', 'status', 'due_at'], name='company_age_company_6d7ad3_idx'), models.Index(fields=['company', 'event_type', 'due_at'], name='company_age_company_4e9558_idx')],
            },
        ),
    ]
