# Generated by Django 5.2.10 on 2026-03-07 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_create_agenda_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Mensaje de presentación de la empresa al profesional.', verbose_name='Mensaje')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('response_message', models.TextField(blank=True, default='', verbose_name='Respuesta del profesional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests_sent', to='company.companyprofile', verbose_name='Empresa')),
                ('professional', models.ForeignKey(limit_choices_to={'user_type': 'professional'}, on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Solicitud de contacto',
                'verbose_name_plural': 'Solicitudes de contacto',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('company', 'professional'), name='uq_pending_contact_request')],
            },
        ),
    ]
