# Generated by Django 5.2.10 on 2026-08-03 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_create_contact_request'),
        ('planillas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa registrada en la plataforma. Al seleccionarla se copian sus datos a los campos del documento, que quedan editables. Dejar vacío si la empresa no es usuaria de la plataforma.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_ergonomicas', to='company.companyprofile', verbose_name='Empresa evaluada'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='cuit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='direccion_establecimiento',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='razon_social',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_ergonomicas', to=settings.AUTH_USER_MODEL, verbose_name='Profesional responsable'),
        ),
    ]
