# Generated by Django 5.2.10 on 2026-08-03 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_create_contact_request'),
        ('planillas', '0002_evaluacion_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'verbose_name': 'Evaluación ergonómica', 'verbose_name_plural': 'Evaluaciones ergonómicas'},
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['usuario', '-fecha_modificacion'], name='idx_eval_usuario_fmod'),
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['empresa', '-fecha_modificacion'], name='idx_eval_empresa_fmod'),
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['cuit'], name='idx_eval_cuit'),
        ),
    ]
