# Generated by Django 5.2.10 on 2026-08-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_create_contact_request'),
        ('planillas', '0003_indices_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilla1',
            name='trabajadores',
            field=models.ManyToManyField(blank=True, help_text='Trabajadores de la nómina alcanzados por este relevamiento. La selección se copia al respaldo histórico sólo si éste está vacío.', related_name='planillas_ergonomicas', to='company.companyworker', verbose_name='Trabajadores relevados'),
        ),
    ]
